/* AGREGAR COLUMNAS A LA TABLA USER_STORE PARA QUE SEA COMPATIBLE CON SPRING SECURITY */

ALTER TABLE user_store
ADD COLUMN IS_ENABLED BOOLEAN;

ALTER TABLE user_store
ADD COLUMN ACCOUNT_NO_EXPIRED BOOLEAN;

ALTER TABLE user_store
ADD COLUMN ACCOUNT_NO_LOCKED BOOLEAN;

ALTER TABLE user_store
ADD COLUMN CREDENTIAL_NO_EXPIRED BOOLEAN;

ALTER TABLE user_store
ADD COLUMN PERMISSIONS VARCHAR(50);

/* CREACION DE LAS TABLAS ROLES, PERMISSIONS, USER_ROLES Y ROLES_PERMISSIONS */

CREATE TABLE ROLES (
    id SERIAL PRIMARY KEY,
    role_name VARCHAR(50)
);

CREATE TABLE PERMISSIONS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE USER_ROLES (
    ROLE_ID BIGINT,
    USER_ID BIGINT
);

CREATE TABLE ROLE_PERMISSIONS (
    PERMISSION_ID BIGINT,
    ROLE_ID BIGINT
);


INSERT INTO ROLES (ROLE_NAME) VALUES ('EMPLOYEE');

INSERT INTO PERMISSIONS (NAME) VALUES ('CREATE');

INSERT INTO ROLE_PERMISSIONS VALUES (1, 1);
INSERT INTO ROLE_PERMISSIONS VALUES (2, 1);


INSERT INTO USER_ROLES VALUES (1, 1);


INSERT INTO USER_STORE (FULL_NAME, PASSWORD, USERNAME, IS_ENABLED, ACCOUNT_NO_EXPIRED, ACCOUNT_NO_LOCKED, CREDENTIALS_NO_EXPIRED)
VALUES ('Sleyther Giulio Calsin Pacsi', '1234', 'sleyther', true, true, true, true),
       ('Daniel Villavicencio Vasquez', '1234', 'daniel', true, true, true, true);

ALTER TABLE USER_STORE
RENAME COLUMN CREDENTIAL_NO_EXPIRED TO CREDENTIALS_NO_EXPIRED;


INSERT INTO ROLES (role_name)
VALUES ('ADMIN'), ('EMPLOYEE');

INSERT INTO PERMISSIONS (name)
VALUES ('CREATE'),
       ('READ'),
       ('UPDATE'),
       ('DELETE'),
       ('REFACTOR');

INSERT INTO USER_ROLES
VALUES (3, 4),
       (4, 5);

INSERT INTO ROLE_PERMISSIONS
VALUES (3, 3),
       (4,3),
       (5,3),
       (6,3),
       (4,4);

ALTER TABLE category
ADD COLUMN IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE SUPPLIER_PRODUCT (
    id_product BIGINT REFERENCES PRODUCT(id),
    id_supplier BIGINT REFERENCES SUPPLIER(id),
    PRIMARY KEY (id_product, id_supplier)
);

/* REMOVER Y ELIMINAR COLUMNA EN TABLA PRODUCT */

ALTER TABLE PRODUCT
DROP CONSTRAINT product_supplier_id_fkey;

ALTER TABLE PRODUCT
DROP COLUMN supplier_id;

/* ALTERAR LAS TABLAS USER_ROLES y ROLE_PERMISSIONS AGREGANDOLES LLAVES FORANEAS */
ALTER TABLE USER_ROLES
ADD CONSTRAINT FK_ROLE
FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID),
ADD CONSTRAINT FK_USER
FOREIGN KEY (USER_ID) REFERENCES USER_STORE(ID),
ADD PRIMARY KEY (ROLE_ID, USER_ID);


ALTER TABLE ROLE_PERMISSIONS
ADD CONSTRAINT FK_PERMISSION
FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(ID),
ADD CONSTRAINT FK_ROLE
FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID),
ADD PRIMARY KEY (PERMISSION_ID, ROLE_ID);